hi_hat_text = label_font.render('Hi Hat', True, colors[actives[0]])
    # screen.blit(hi_hat_text, (30, 30))
    # snare_text = label_font.render('Snare', True, colors[actives[1]])
    # screen.blit(snare_text, (30, 130))
    # kick_text = label_font.render('    OFF/ON', True, colors[actives[2]])
    # screen.blit(kick_text, (30, 230))
    # crash_text = label_font.render('    OFF/ON', True, colors[actives[3]])
    # screen.blit(crash_text, (30, 330))
    # clap_text = label_font.render('    OFF/ON', True, colors[actives[4]])
    # screen.blit(clap_text, (30, 430))
    # tom_text = label_font.render('    OFF/ON', True, colors[actives[5]])
    # screen.blit(tom_text, (30, 530))